export { version } from '../package.json';  //暴露模块版本

export { default as Document } from './Document';
export { default as ServiceProvider } from './enums/ServiceProvoder';
export { default as Audio } from './elements/Audio';
export { default as Action } from './elements/Action';
export { default as AutoBreaths } from './elements/AutoBreaths';
export { default as Break } from './elements/Break';
export { default as BackgroundAudio } from './elements/BackgroundAudio';
export { default as Bookmark } from './elements/Bookmark';
export { default as ExpressAs } from './elements/ExpressAs';
export { default as Emphasis } from './elements/Emphasis';
export { default as Emotion } from './elements/Emotion';
export { default as Effect } from './elements/Effect';
export { default as Mark } from './elements/Mark';
export { default as Language } from './elements/Language';
export { default as Lexicon } from './elements/Lexicon';
export { default as Paragraph } from './elements/Paragraph';
export { default as Parallel } from './elements/Parallel';
export { default as Phoneme } from './elements/Phoneme';
export { default as Prosody } from './elements/Prosody';
export { default as Raw } from './elements/Raw';
export { default as SayAs } from './elements/SayAs';
export { default as Sentence } from './elements/Sentence';
export { default as Silence } from './elements/Silence';
export { default as Subsitute } from './elements/Subsitute';
export { default as Sequential } from './elements/Sequential';
export { default as SoundEvent } from './elements/SoundEvent';
export { default as Voice } from './elements/Voice';
export { default as Word } from './elements/Word';
export * as elements from './elements';
